name: hugo
services:
  hugo:
    image: ghcr.io/joshyorko/joshblog-hugo-terminal:latest
    ports:
      - "1313:1313"
    volumes:
      - ./:/site
    command: ["hugo", "server", "--bind", "0.0.0.0",  "-t", "terminal", "--buildDrafts", "--buildFuture"]


