name: hugo
services:
  hugo:
    build:
      context: .
    ports:
      - "1313:1313"
    volumes:
      - ./:/site
    command: ["hugo", "server", "--bind", "0.0.0.0", "--port", "1313", "-t", "terminal", "--watch", "--buildDrafts", "--buildFuture", "--noHTTPCache"]


