name: Deploy Hugo Site

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Get Hugo Modules
        run: hugo mod get

      - name: Build
        run: hugo --theme terminal --buildDrafts --buildFuture --buildExpired --noHTTPCache

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./public
          allow_empty_commit: true
          keep_files: true
